[package]
name = "nnqt"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.15"
ndarray-rand = "0.14"
rand = "0.8"
rand_distr = "0.4"
csv = "1.1"
plotters = "0.3.0"
itertools = "0.10"
plotters-backend = "0.3"
