[package]
name = "nnqtnew"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.12.1", features = ["tch"] }
burn-tch = "0.12.1"
ndarray = "0.15"
csv = "1.3"
plotters = "0.3"
polars = { version = "0.37", features = ["csv"] }